[package]
name = "sql_model_derive"
version = "0.1.0"
edition = "2021"

# IMPORTANTE: Procedural Macro
[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
